# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='hecho',
            field=models.BooleanField(default=False),
        ),
    ]
