# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_todo_hecho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='fecha_creado',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='hecho',
            new_name='done',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='fecha_finalizado',
            new_name='ended_date',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='propietario',
            new_name='owner',
        ),
    ]
